---
- name: Laraval App
  hosts: all
  remote_user: root
  become: yes

  vars_files:
    - vars/config

  tasks:
    - name: Upgrade System
      apt: upgrade=dist update_cache=yes
      become: yes

    - name: Install Apache2, PHP and dependencies
      ansible.builtin.package:
        name:
          - apache2
          - php{{ php_version }}
          - php{{ php_version }}-mbstring
          - php{{ php_version }}-xml
          - libapache2-mod-php
          - php{{ php_version }}-zip
          - php{{ php_version }}-mysql
          - php{{ php_version }}-pgsql
          - php{{ php_version }}-xml
          - php{{ php_version }}-dev
          - php{{ php_version }}-gd
          - php{{ php_version }}-curl
        state: present
        update_cache: yes

    - name: download composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer

    - name: install composer
      shell: php /tmp/composer --install-dir=/usr/local/bin
      become: yes

    - name: rename composer executable
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      become: yes

    - name: set permissions for composer file
