---
- name: postgres
  hosts: all
  remote_user: root
  become: yes

  vars_files:
    - vars/config

  tasks:

    - name: Create a directory called script
      ansible.builtin.file:
        path: /root/script/
        state: directory

    - name: Copy bash script
      copy:
        src: postgres.sh
        dest: /root/script
        mode: '0777'
        owner: root

    - name: run script
      shell: |
        cd /root/script
        bash postgres.sh
